# Site settings
title: MasterJ's Blog
email: ronchaos@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Enjoy Lift Style
baseurl: "/clean" # the subpath of your site, e.g. /blog/
url: "https://masterjj.github.io/clean/"
# the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: masterjj 

# Build settings
markdown: kramdown
